server {
    # 1. Какой порт слушать наружу
    listen 80;
    server_name localhost;

    # 2. Раздача фронтенда (Статика)
    location / {
        root /usr/share/nginx/html;
        index views/dashboard.html;
        try_files $uri $uri/ /views/dashboard.html;
    }

    # 3. Перенаправление на Go-бэкенд (API)
    location /api/ {
        # Отрезаем приставку /api/ перед отправкой в Go
        rewrite ^/api/(.*)$ /$1 break;

        # Пересылаем запрос в контейнер с Go (внутри сети Docker)
        proxy_pass http://backend:8080;

        # Прокидываем реальные IP-адреса пользователя, чтобы Go их видел в логах
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}