// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: task/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTasksByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByUserIDRequest) Reset() {
	*x = GetTasksByUserIDRequest{}
	mi := &file_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByUserIDRequest) ProtoMessage() {}

func (x *GetTasksByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetTasksByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type TaskIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskIDRequest) Reset() {
	*x = TaskIDRequest{}
	mi := &file_task_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIDRequest) ProtoMessage() {}

func (x *TaskIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIDRequest.ProtoReflect.Descriptor instead.
func (*TaskIDRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NewDescription string                 `protobuf:"bytes,2,opt,name=new_description,json=newDescription,proto3" json:"new_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDescriptionRequest) Reset() {
	*x = UpdateDescriptionRequest{}
	mi := &file_task_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDescriptionRequest) ProtoMessage() {}

func (x *UpdateDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDescriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDescriptionRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateDescriptionRequest) GetNewDescription() string {
	if x != nil {
		return x.NewDescription
	}
	return ""
}

type MarkAsDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsDoneRequest) Reset() {
	*x = MarkAsDoneRequest{}
	mi := &file_task_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsDoneRequest) ProtoMessage() {}

func (x *MarkAsDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsDoneRequest.ProtoReflect.Descriptor instead.
func (*MarkAsDoneRequest) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAsDoneRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkAsDoneRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserTaskId    int64                  `protobuf:"varint,5,opt,name=user_task_id,json=userTaskId,proto3" json:"user_task_id,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Task) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Task) GetUserTaskId() int64 {
	if x != nil {
		return x.UserTaskId
	}
	return 0
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_task_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{7}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_task_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_task_task_proto_rawDescGZIP(), []int{8}
}

var File_task_task_proto protoreflect.FileDescriptor

const file_task_task_proto_rawDesc = "" +
	"\n" +
	"\x0ftask/task.proto\x12\x04task\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"2\n" +
	"\x17GetTasksByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"\x1f\n" +
	"\rTaskIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\\\n" +
	"\x18UpdateDescriptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12'\n" +
	"\x0fnew_description\x18\x02 \x01(\tR\x0enewDescription\";\n" +
	"\x11MarkAsDoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"\xd8\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12 \n" +
	"\fuser_task_id\x18\x05 \x01(\x03R\n" +
	"userTaskId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\",\n" +
	"\bTaskList\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".task.TaskR\x05tasks\"\a\n" +
	"\x05Empty2\x88\x04\n" +
	"\vTaskService\x121\n" +
	"\n" +
	"CreateTask\x12\x17.task.CreateTaskRequest\x1a\n" +
	".task.Task\x12A\n" +
	"\x10GetTasksByUserID\x12\x1d.task.GetTasksByUserIDRequest\x1a\x0e.task.TaskList\x12H\n" +
	"\x17GetRemovedTasksByUserID\x12\x1d.task.GetTasksByUserIDRequest\x1a\x0e.task.TaskList\x12+\n" +
	"\aGetTask\x12\x14.task.GetTaskRequest\x1a\n" +
	".task.Task\x12.\n" +
	"\n" +
	"DeleteTask\x12\x13.task.TaskIDRequest\x1a\v.task.Empty\x125\n" +
	"\x11DeleteForeverTask\x12\x13.task.TaskIDRequest\x1a\v.task.Empty\x12/\n" +
	"\vRecoverTask\x12\x13.task.TaskIDRequest\x1a\v.task.Empty\x12@\n" +
	"\x11UpdateDescription\x12\x1e.task.UpdateDescriptionRequest\x1a\v.task.Empty\x122\n" +
	"\n" +
	"MarkAsDone\x12\x17.task.MarkAsDoneRequest\x1a\v.task.EmptyB\x11Z\x0ftodo-proto/taskb\x06proto3"

var (
	file_task_task_proto_rawDescOnce sync.Once
	file_task_task_proto_rawDescData []byte
)

func file_task_task_proto_rawDescGZIP() []byte {
	file_task_task_proto_rawDescOnce.Do(func() {
		file_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_task_proto_rawDesc), len(file_task_task_proto_rawDesc)))
	})
	return file_task_task_proto_rawDescData
}

var file_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_task_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),        // 0: task.CreateTaskRequest
	(*GetTasksByUserIDRequest)(nil),  // 1: task.GetTasksByUserIDRequest
	(*GetTaskRequest)(nil),           // 2: task.GetTaskRequest
	(*TaskIDRequest)(nil),            // 3: task.TaskIDRequest
	(*UpdateDescriptionRequest)(nil), // 4: task.UpdateDescriptionRequest
	(*MarkAsDoneRequest)(nil),        // 5: task.MarkAsDoneRequest
	(*Task)(nil),                     // 6: task.Task
	(*TaskList)(nil),                 // 7: task.TaskList
	(*Empty)(nil),                    // 8: task.Empty
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_task_task_proto_depIdxs = []int32{
	9,  // 0: task.Task.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 1: task.TaskList.tasks:type_name -> task.Task
	0,  // 2: task.TaskService.CreateTask:input_type -> task.CreateTaskRequest
	1,  // 3: task.TaskService.GetTasksByUserID:input_type -> task.GetTasksByUserIDRequest
	1,  // 4: task.TaskService.GetRemovedTasksByUserID:input_type -> task.GetTasksByUserIDRequest
	2,  // 5: task.TaskService.GetTask:input_type -> task.GetTaskRequest
	3,  // 6: task.TaskService.DeleteTask:input_type -> task.TaskIDRequest
	3,  // 7: task.TaskService.DeleteForeverTask:input_type -> task.TaskIDRequest
	3,  // 8: task.TaskService.RecoverTask:input_type -> task.TaskIDRequest
	4,  // 9: task.TaskService.UpdateDescription:input_type -> task.UpdateDescriptionRequest
	5,  // 10: task.TaskService.MarkAsDone:input_type -> task.MarkAsDoneRequest
	6,  // 11: task.TaskService.CreateTask:output_type -> task.Task
	7,  // 12: task.TaskService.GetTasksByUserID:output_type -> task.TaskList
	7,  // 13: task.TaskService.GetRemovedTasksByUserID:output_type -> task.TaskList
	6,  // 14: task.TaskService.GetTask:output_type -> task.Task
	8,  // 15: task.TaskService.DeleteTask:output_type -> task.Empty
	8,  // 16: task.TaskService.DeleteForeverTask:output_type -> task.Empty
	8,  // 17: task.TaskService.RecoverTask:output_type -> task.Empty
	8,  // 18: task.TaskService.UpdateDescription:output_type -> task.Empty
	8,  // 19: task.TaskService.MarkAsDone:output_type -> task.Empty
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_task_task_proto_init() }
func file_task_task_proto_init() {
	if File_task_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_task_proto_rawDesc), len(file_task_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_task_proto_goTypes,
		DependencyIndexes: file_task_task_proto_depIdxs,
		MessageInfos:      file_task_task_proto_msgTypes,
	}.Build()
	File_task_task_proto = out.File
	file_task_task_proto_goTypes = nil
	file_task_task_proto_depIdxs = nil
}
