services:

  postgres_db:
    image: postgres:15-alpine
    container_name: todo_postgres_compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_migrations:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations 
    command: -path=/migrations -database="postgres://postgres:secret@postgres_db:5432/todo_db?sslmode=disable" up
    depends_on:
      - postgres_db


  redis_db:
    image: redis:7-alpine
    container_name: todo_redis_compose
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

 
  backend:
    build: ./backend # Указываем на папку с Go-кодом
    env_file:
      - ./backend/.env # Путь к твоему файлу окружения
    container_name: todo_app_compose
    ports:
      - "8080:8080"
    depends_on:
      db_migrations:
        condition: service_completed_successfully
      redis_db: # Ждем, пока поднимется Redis
        condition: service_started
    environment:
      DATABASE_URL: "postgres://postgres:secret@postgres_db:5432/todo_db?sslmode=disable"
      REDIS_HOST: "redis_db" # Передаем бэкенду имя контейнера Redis
      REDIS_PORT: "6379"

  # 5. Наш веб-сервер Nginx + Фронтенд
  nginx:
    image: nginx:alpine
    container_name: todo_nginx_compose
    ports:
      - "80:80" # Слушает стандартный порт для сайтов
    volumes:
      # Монтируем конфигурацию, которую мы написали на прошлом шаге
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Монтируем всю модульную структуру фронтенда целиком
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata: 