// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: usertg/usertg.proto

package usertg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserTgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserTgRequest) Reset() {
	*x = RegisterUserTgRequest{}
	mi := &file_usertg_usertg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserTgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserTgRequest) ProtoMessage() {}

func (x *RegisterUserTgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usertg_usertg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserTgRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserTgRequest) Descriptor() ([]byte, []int) {
	return file_usertg_usertg_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserTgRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *RegisterUserTgRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegisterUserTgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserTgResponse) Reset() {
	*x = RegisterUserTgResponse{}
	mi := &file_usertg_usertg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserTgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserTgResponse) ProtoMessage() {}

func (x *RegisterUserTgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usertg_usertg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserTgResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserTgResponse) Descriptor() ([]byte, []int) {
	return file_usertg_usertg_proto_rawDescGZIP(), []int{1}
}

type GetUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIDRequest) Reset() {
	*x = GetUserByTgIDRequest{}
	mi := &file_usertg_usertg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIDRequest) ProtoMessage() {}

func (x *GetUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usertg_usertg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_usertg_usertg_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByTgIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *GetUserByTgIDRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserTg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTg) Reset() {
	*x = UserTg{}
	mi := &file_usertg_usertg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTg) ProtoMessage() {}

func (x *UserTg) ProtoReflect() protoreflect.Message {
	mi := &file_usertg_usertg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTg.ProtoReflect.Descriptor instead.
func (*UserTg) Descriptor() ([]byte, []int) {
	return file_usertg_usertg_proto_rawDescGZIP(), []int{3}
}

func (x *UserTg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserTg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserTg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_usertg_usertg_proto protoreflect.FileDescriptor

const file_usertg_usertg_proto_rawDesc = "" +
	"\n" +
	"\x13usertg/usertg.proto\x12\x06usertg\"H\n" +
	"\x15RegisterUserTgRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x18\n" +
	"\x16RegisterUserTgResponse\"G\n" +
	"\x14GetUserByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"M\n" +
	"\x06UserTg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId2\x9f\x01\n" +
	"\rUserTgService\x12O\n" +
	"\x0eRegisterUserTg\x12\x1d.usertg.RegisterUserTgRequest\x1a\x1e.usertg.RegisterUserTgResponse\x12=\n" +
	"\rGetUserByTgID\x12\x1c.usertg.GetUserByTgIDRequest\x1a\x0e.usertg.UserTgB\x13Z\x11todo-proto/usertgb\x06proto3"

var (
	file_usertg_usertg_proto_rawDescOnce sync.Once
	file_usertg_usertg_proto_rawDescData []byte
)

func file_usertg_usertg_proto_rawDescGZIP() []byte {
	file_usertg_usertg_proto_rawDescOnce.Do(func() {
		file_usertg_usertg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usertg_usertg_proto_rawDesc), len(file_usertg_usertg_proto_rawDesc)))
	})
	return file_usertg_usertg_proto_rawDescData
}

var file_usertg_usertg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_usertg_usertg_proto_goTypes = []any{
	(*RegisterUserTgRequest)(nil),  // 0: usertg.RegisterUserTgRequest
	(*RegisterUserTgResponse)(nil), // 1: usertg.RegisterUserTgResponse
	(*GetUserByTgIDRequest)(nil),   // 2: usertg.GetUserByTgIDRequest
	(*UserTg)(nil),                 // 3: usertg.UserTg
}
var file_usertg_usertg_proto_depIdxs = []int32{
	0, // 0: usertg.UserTgService.RegisterUserTg:input_type -> usertg.RegisterUserTgRequest
	2, // 1: usertg.UserTgService.GetUserByTgID:input_type -> usertg.GetUserByTgIDRequest
	1, // 2: usertg.UserTgService.RegisterUserTg:output_type -> usertg.RegisterUserTgResponse
	3, // 3: usertg.UserTgService.GetUserByTgID:output_type -> usertg.UserTg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usertg_usertg_proto_init() }
func file_usertg_usertg_proto_init() {
	if File_usertg_usertg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usertg_usertg_proto_rawDesc), len(file_usertg_usertg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usertg_usertg_proto_goTypes,
		DependencyIndexes: file_usertg_usertg_proto_depIdxs,
		MessageInfos:      file_usertg_usertg_proto_msgTypes,
	}.Build()
	File_usertg_usertg_proto = out.File
	file_usertg_usertg_proto_goTypes = nil
	file_usertg_usertg_proto_depIdxs = nil
}
