// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: usertg/usertg.proto

package usertg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserTgService_RegisterUserTg_FullMethodName = "/usertg.UserTgService/RegisterUserTg"
	UserTgService_GetUserByTgID_FullMethodName  = "/usertg.UserTgService/GetUserByTgID"
)

// UserTgServiceClient is the client API for UserTgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserTgServiceClient interface {
	RegisterUserTg(ctx context.Context, in *RegisterUserTgRequest, opts ...grpc.CallOption) (*RegisterUserTgResponse, error)
	GetUserByTgID(ctx context.Context, in *GetUserByTgIDRequest, opts ...grpc.CallOption) (*UserTg, error)
}

type userTgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserTgServiceClient(cc grpc.ClientConnInterface) UserTgServiceClient {
	return &userTgServiceClient{cc}
}

func (c *userTgServiceClient) RegisterUserTg(ctx context.Context, in *RegisterUserTgRequest, opts ...grpc.CallOption) (*RegisterUserTgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserTgResponse)
	err := c.cc.Invoke(ctx, UserTgService_RegisterUserTg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userTgServiceClient) GetUserByTgID(ctx context.Context, in *GetUserByTgIDRequest, opts ...grpc.CallOption) (*UserTg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserTg)
	err := c.cc.Invoke(ctx, UserTgService_GetUserByTgID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserTgServiceServer is the server API for UserTgService service.
// All implementations must embed UnimplementedUserTgServiceServer
// for forward compatibility.
type UserTgServiceServer interface {
	RegisterUserTg(context.Context, *RegisterUserTgRequest) (*RegisterUserTgResponse, error)
	GetUserByTgID(context.Context, *GetUserByTgIDRequest) (*UserTg, error)
	mustEmbedUnimplementedUserTgServiceServer()
}

// UnimplementedUserTgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserTgServiceServer struct{}

func (UnimplementedUserTgServiceServer) RegisterUserTg(context.Context, *RegisterUserTgRequest) (*RegisterUserTgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUserTg not implemented")
}
func (UnimplementedUserTgServiceServer) GetUserByTgID(context.Context, *GetUserByTgIDRequest) (*UserTg, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByTgID not implemented")
}
func (UnimplementedUserTgServiceServer) mustEmbedUnimplementedUserTgServiceServer() {}
func (UnimplementedUserTgServiceServer) testEmbeddedByValue()                       {}

// UnsafeUserTgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserTgServiceServer will
// result in compilation errors.
type UnsafeUserTgServiceServer interface {
	mustEmbedUnimplementedUserTgServiceServer()
}

func RegisterUserTgServiceServer(s grpc.ServiceRegistrar, srv UserTgServiceServer) {
	// If the following call panics, it indicates UnimplementedUserTgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserTgService_ServiceDesc, srv)
}

func _UserTgService_RegisterUserTg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserTgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTgServiceServer).RegisterUserTg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserTgService_RegisterUserTg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTgServiceServer).RegisterUserTg(ctx, req.(*RegisterUserTgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserTgService_GetUserByTgID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTgIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTgServiceServer).GetUserByTgID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserTgService_GetUserByTgID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTgServiceServer).GetUserByTgID(ctx, req.(*GetUserByTgIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserTgService_ServiceDesc is the grpc.ServiceDesc for UserTgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserTgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usertg.UserTgService",
	HandlerType: (*UserTgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUserTg",
			Handler:    _UserTgService_RegisterUserTg_Handler,
		},
		{
			MethodName: "GetUserByTgID",
			Handler:    _UserTgService_GetUserByTgID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usertg/usertg.proto",
}
